### ISSUE TITLE
Comments section using Giscus and not utterances

### ISSUE THREAD

**Issue by konrad-wila** [elibroftw/blog.elijahlopez.ca#19]
The blog is using Giscus for comments and requires the installation of Giscus and generation of repo-id, category-id, etc. and not Utterances as suggested in step 10 of the tutorial.

https://blog.elijahlopez.ca/posts/hugo-tutorial/

https://giscus.app/

**Comment by konrad-wila** [comment]
All the comments in the discussions tab are posted by the giscus bot as well

**Comment by elibroftw** [comment]
I fixed this issue yesterday ahah, but yeah the caching is probably what got you messed up.
